#!/bin/sh


if [ -f ./$1 ]
then
    echo "..."
else
    echo "don't found bin-file "
    echo "usage> ./update_rev2.sh [file name] "
	echo "     ex) ./update_rev2.sh rev_2v1.tar.xz "
    exit 1
fi

FILE=$1

cd /
rm -rf /emulator_bak
mv -ff /emulator /emulator_bak
sync

tar -xvf $FILE
sync


echo "     ============================"
echo "     ============================"
echo "     Done~! power on.off"
echo "     reboot~! power on.off"
echo "     ============================"
echo "     ============================"
