#!/bin/sh


if [ -f ./$1 ]
then
    echo "..."
else
    echo "don't found bin-file "
    echo "usage> ./update_rev1.sh [file name] "
	echo "     ex) ./update_rev1.sh rev_1v1.tar.xz "
    exit 1
fi

FILE=$1

cd /
rm -rf /emulator_bak
mv -ff /emulator /emulator_bak
sync

tar -xvf $FILE
cp /python-periphery.tar.xz /emulator
cd /emulator
sync

tar -xvf ./python-periphery.tar.xz
sync

cd /emulator/python-periphery
python3 setup.py install
sync

echo "     ============================"
echo "     ============================"
echo "     Done~! power on.off"
echo "     reboot~! power on.off"
echo "     ============================"
echo "     ============================"
